pre-release-commit-message = "ðŸš€ chore(release): version "
shared-version = true
sign-commit = true
tag-message = ""
tag-prefix = ""
publish = false
push = true
tag = true
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "" ]
