contact_links:
  - name: ğŸ™ Q&A (GitHub Discussions)
    url: https://github.com/t1ltxz-gxd/serenity_template/discussions/categories/q-a
    about: "Ask questions and get answers from the community."
